version: '3.5'
services:
  api:
    image: ldilone25/task-management-backend:1.0.0
    container_name: task-management-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"       

  web:
    image: ldilone25/task-management-frontend:1.0.0
    container_name: task-management-frontend
    depends_on:
      - api    
    restart: unless-stopped
    ports:
      - "5001:80"    
    
