version: '3.5'
services:
  api:
    build: .    
    image: task-management-backend:1.0.0
    container_name: task_manager_backend
    restart: unless-stopped
    env_file:
      - ./.env    
    ports:
      - "5000:5000"
